version: "3.9"

services:
  backend:
    build:
      context: .
      target: prod
    container_name: express-ts-app-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo-db-prod
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-prod:/data/db

volumes:
  mongo-data-prod:
