version: "3.9"

services:
  backend:
    build:
      context: .
      target: dev
    container_name: express-ts-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    command: mongod --quiet
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d  


volumes:
  mongo-data:
